layout_spectrum: 0.4265308922622353
typography_spectrum: 0.5561194159090519
color:
  saturation: 0.38542727706953883
  brandStrength: 0.7187574282288551
  rhythmicContrast: 0.21348909568041563
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  lightness: 0.21549363271333277
author:
  email: contact@tinyblogofatinyjourney.com
logo: null
name: Tiny Blog of a Tiny Journey
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: a Tiny Blog
description: of a Tiny Journey
